---
- name: CREATE Public IP Address for temporary VIP
  delegate_to: localhost
  azure_rm_publicipaddress:
    resource_group: "rg-{{ extra_hubplatform_name }}"
    allocation_method: Static
    domain_name: "{{ extra_cluster_name }}-{{ extra_hubplatform_name }}"
    name: "vip-{{ extra_hubplatform_name }}-{{ extra_cluster_name }}"
    location: "{{ extra_location }}"
    sku: 'Standard'
    idle_timeout: 30
    version: 'ipv4'
    tags:
      Name: "vip-{{ extra_hubplatform_name }}-{{ extra_cluster_name }}"
      owner: "{{ owner }}"

- name: SET var_backend_address_pools
  set_fact:
    var_backend_address_pools: "[ {
    'name': 'pool-{{ extra_cluster_name }}-external'
    } ]"

- name: SET var_frontend_ip_configurations
  set_fact:
    var_frontend_ip_configurations: "[ {
    'name': 'vip-empty',
    'public_ip_address': 'vip-{{ extra_hubplatform_name }}-{{ extra_cluster_name }}'
    } ]"

- name: SET var_probes
  set_fact:
    var_probes: "[ {
    'name': 'hc-{{ extra_cluster_name }}-external-empty',
    'port': 1024,
    'protocol': 'Tcp',
    'interval': 5,
    'fail_count': 2
    } ]"

- name: SET var_load_balancing_rules
  set_fact:
    var_load_balancing_rules: "[ {
    'name': 'rule-{{ extra_cluster_name }}-external-empty',
    'frontend_ip_configuration': 'vip-empty',
    'backend_address_pool': 'pool-{{ extra_cluster_name }}-external',
    'protocol': 'Tcp',
    'load_distribution': 'Default',
    'frontend_port': 1024,
    'backend_port': 1024,
    'probe': 'hc-{{ extra_cluster_name }}-external-empty',
    } ]"

- name: UPDATE external load balancer
  delegate_to: localhost
  azure_rm_loadbalancer:
    resource_group: "rg-{{ extra_hubplatform_name }}"
    name: "lb-{{ extra_cluster_name }}-external"
    location: "{{ extra_location }}"
    sku: Standard
    frontend_ip_configurations: "{{ var_frontend_ip_configurations }}"
    backend_address_pools: "{{ var_backend_address_pools }}"
    probes: "{{ var_probes }}"
    load_balancing_rules: "{{ var_load_balancing_rules }}"

- name: DELETE Public IP Address for VIP
  delegate_to: localhost
  azure_rm_publicipaddress:
    resource_group: "rg-{{ extra_hubplatform_name }}"
    name: "vip-{{ extra_hubplatform_name }}-{{ extra_app_name }}"
    state: absent





...