---
# default variables
activity:
tmos_version : "15.1.002000"
f5_rpm_do_version: "1.11.1"
f5_rpm_do_build_version: "1"
f5_rpm_as3_version: "3.18.0"
f5_rpm_as3_build_version: "4"
f5_rpm_ts_version: "1.10.0"
f5_rpm_ts_build_version: "2"
...