---
- import_role:
    name: f5devcentral.f5ansible

- name: Discover a device and import config
  delegate_to: localhost
  bigiq_device_discovery:
    state: "{{ extra_bigiq_device_discovery_state }}"
    device_address: "{{ extra_ip_mgt }}"
    device_port: "{{ extra_port_mgt }}"
    device_username: "{{ extra_admin_user }}"
    device_password: "{{ extra_admin_password }}"
    modules: "{{ extra_device_modules }}"
    conflict_policy: use_bigiq
    versioned_conflict_policy: use_bigiq
    device_conflict_policy: use_bigiq
    use_bigiq_sync: yes
    statistics:
      enable: yes
    force: yes
    ha_name: "failoverGroup-{{ extra_platform_name }}-{{ extra_cluster_name }}"
    provider:
      user: "{{ extra_bigiq_admin_user }}"
      password: "{{ extra_bigiq_admin_password }}"
      server: "{{ extra_bigiq_ip_mgt }}"
      server_port: "{{ extra_bigiq_port_mgt }}"
      validate_certs: no
  when: extra_functional_type == "awaf"










