---

- name: Get BIG-IQ Token POST /mgmt/shared/authn/login
  uri:
    url: https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/authn/login
    method: POST
    headers:
      Content-Type: application/json
    body: "{{ lookup('template','bigiq_auth.jinja2') }}"
    body_format: json
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: auth


- name: URI DELETE Tenant                                                                            
  uri:                                                                                             
    url: "https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/appsvcs/declare/{{ extra_app_name }}?async=true"                           
    method: "DELETE"
    headers:
        X-F5-Auth-Token: "{{auth.json.token.token}}"
    #user: "{{ extra_admin_user }}"                                                                                 
    #password: "{{ extra_admin_password }}"                                                                                                                                                      
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: json_response

- debug:
    var: json_response.json





### LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

- name: Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
  uri:
    url: https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
    method: GET
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: json_response_task

- debug:
    var: json_response_task.json

- name: LOOP Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
  uri:
    url: https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
    method: GET
    headers:
      Content-Type: application/json
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    status_code: 200, 202
    validate_certs: false
  register: json_response_task
  until: "json_response_task.json[0].results != 'pending'"
  retries: 20
  delay: 15

- debug:
    var: json_response_task.json
