---
- name: Restart restnoded
  bigip_command:
    commands: restart sys service restnoded
    provider:
      user: "{{ extra_bigip_target_admin_user }}"
      password: "{{ extra_bigip_target_admin_password }}"
      server: "{{ item.management }}"
      server_port: "{{ extra_bigip_target_port_mgt }}"
      validate_certs: no
  delegate_to: localhost
  loop: "{{ stats_self_ips }}"






