---
- name: CREATE CRT App
  copy:
    content: "{{ extra_app_crt }}"
    dest: "/etc/ssl/certs/{{ extra_app_name | lower }}.crt"

- name: CREATE KEY App
  copy:
    content: "{{ extra_app_key }}"
    dest: "/etc/ssl/private/{{ extra_app_name | lower }}.key"
    mode: '0400'

- name: CREATE conf App
  copy: content="{{ lookup('template', 'app_app_protect.conf') }}" dest="/etc/nginx/conf.d/{{ extra_app_name | lower }}.conf"

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: SYNC cluster
  command: nginx-sync.sh
  register: var_sync_stdout

- debug:
    msg: "stdout={{ var_sync_stdout }}"
...