---
- name: CREATE CRT App
  copy:
    content: "{{ extra_app_crt }}"
    dest: "/etc/ssl/certs/{{ extra_app_name | lower }}.crt"

- name: CREATE KEY App
  copy:
    content: "{{ extra_app_key }}"
    dest: "/etc/ssl/private/{{ extra_app_name | lower }}.key"
    mode: '0400'

- name: CREATE conf App
  copy: content="{{ lookup('template', 'app_app_protect.conf') }}" dest="/etc/nginx/conf.d/{{ extra_app_name | lower }}.conf"

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: INIT var_sync_nodes
  set_fact:
    var_sync_nodes: ""

- name: SET var_sync_nodes
  set_fact:
    var_sync_nodes: "{{ var_sync_nodes }} {{ item.management }}"
  loop: "{{ stats_self_ips }}"
  when: item.protect_from_scale_in != "True"

- debug:
    msg: "var_sync_nodes={{ var_sync_nodes }}"

- name: SYNC cluster
  command: nginx-sync.sh
  register: var_sync_stdout
  when: var_sync_nodes != ""

- debug:
    msg: "stdout={{ var_sync_stdout }}"
...