---
- name: CREATE authorized_keys repo
  file:
    path: /root/.ssh/
    state: directory

- name: COPY Master authorized_keys on Slaves
  copy:
    content: "{{ stats_master_key }}"
    dest: "/root/.ssh/authorized_keys"
    mode: '0400'

- name: ALLOW ssh root from Master
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitRootLogin without-password"
    create: no

- name: START sshd service
  systemd:
    state: started
    name: sshd






...