---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: CREATE ansible-playbook in-memory inventory
    add_host:
      groups: "vmss-from-workflow"
      hostname: "{{ extra_vmss_name }}-{{ item.instance_id }}"
      ansible_host: "{{ item.management }}"
      ansible_port: 22
    loop: "{{ stats_self_ips }}"
    # https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#intro-inventory
    # https://docs.microsoft.com/en-us/azure/developer/ansible/vm-scale-set-deploy-app

# Define N+ and NAP specific version
# $ yum --disablerepo="*" --enablerepo="nginx-plus" list available

- hosts: vmss-from-workflow
  gather_facts: yes
  become: true
  roles:
    - { role: nginxinc.nginx }
  vars:
    nginx_type: plus
    # nginx_version: -22-1.el7.ngx
    nginx_start: true
    nginx_license:
      certificate: "{{extra_nginx_licence_dir}}/nginx-repo.crt"
      key: "{{extra_nginx_licence_dir}}/nginx-repo.key"
    nginx_delete_license: false
    nginx_cleanup_config: true
    nginx_cleanup_config_path:
      - /etc/nginx/conf.d/default.conf
    nginx_rest_api_enable: true
    nginx_rest_api_src: http/api.conf.j2
    nginx_rest_api_location: /etc/nginx/conf.d/api.conf
    nginx_rest_api_port: "{{ ansible_host }}:8080"
    nginx_rest_api_write: true
    nginx_rest_api_dashboard: true

- hosts: vmss-from-workflow
  gather_facts: yes
  become: true
  roles:
    - { role: ansible-role-nginx-app-protect }
  vars:
    app_protect_state: present
    # app_protect_version: -22+2.52.5-1.el7.ngx
    app_protect_selinux: false
    app_protect_install_signatures: true
    app_protect_configure: true
    app_protect_security_policy_template_enable: true
    security_policy_enforcement_mode: blocking
    app_protect_log_policy_template_enable: true
    log_policy_filter_request_type: all
    log_policy_syslog_target: "{{extra_app_protect_monitor_ip}}:5144"
    nginx_license:
      certificate: "{{extra_nginx_licence_dir}}/nginx-repo.crt"
      key: "{{extra_nginx_licence_dir}}/nginx-repo.key"





