--- 
#bigiq
extra_ip_mgt: 212.121.177.199
extra_port_mgt: 10443
extra_admin_user: admin
extra_admin_password: F5N3tworks

#bigip
extra_bigip_target: bigip1

extra_template: template_http_bigiq_patch.jinja2
#add or remove
extra_operation: add

# app
extra_tenant: tenant_POC_BT2
extra_application: myapp43
# only used for add
extra_vip: 10.42.1.131
extra_pool:
  servicePort: 8090
  members:
  - 10.42.1.200

