--- 
extra_ip_mgt: 10.102.0.136
extra_admin_user: admin
extra_admin_password: F5N3tworks
extra_template: template_http.jinja2
extra_tenant: tenant_POC_BT1
extra_application: myapp
extra_vip: 10.42.10.101
extra_pool:
  servicePort: 8080
  members:
  - 10.1.20.20
  - 10.1.20.21
  - 10.1.20.22
