--- 
#bigip
extra_ip_mgt: 10.102.0.136
extra_admin_user: admin
extra_admin_password: F5N3tworks

extra_template: template_http_patch.jinja2
#add or remove
extra_operation: remove

# app
extra_tenant: tenant_POC_BT11
extra_application: myapp1
# only used for add
extra_vip: 10.42.10.1
extra_pool:
  servicePort: 8090
  members:
  - 10.1.20.11
  - 10.1.20.12
  - 10.1.20.13
